/**
 * Daily hype line for the dashboard. One per day of the year (stable per day),
 * so it changes every morning. Wolf-of-Wall-Street / grindset energy: money,
 * closing, discipline, no excuses. Personal dashboard — unfiltered by design.
 */
export const HYPE_LINES: string[] = [
  "The only thing between you and rich is the bullshit story you keep telling yourself.",
  "Pick up the fucking phone. The money's on the other end of it.",
  "Broke is a mindset and you're about to evict it.",
  "Act like the man you want to become until the bank statement agrees.",
  "Nobody's coming to save you. Good. You don't need saving, you need closing.",
  "Discipline is doing it when you'd rather do anything else. Do it.",
  "Winners get up. Everybody else negotiates with the snooze button.",
  "The market doesn't care about your feelings. Neither should you. Dial.",
  "You want the Bugatti? It's hiding behind 100 no's. Go dig.",
  "Comfort is for retired men. You're not retired. Move.",
  "Every closer was once a coward who picked up the phone anyway.",
  "Money loves speed and hates excuses. Pick a side.",
  "Your competition is soft and asleep. Rob them blind while they dream.",
  "Be the hardest worker in the room or get used to losing in it.",
  "One more dial. That sentence built every empire on earth.",
  "Scared money stays broke. Bet the house on yourself.",
  "You eat what you kill. So go fucking hunt.",
  "Mediocrity is a choice you make every morning you don't go hard.",
  "The grind doesn't ask how you feel. Clock in and shut up.",
  "Be so relentless they think it's luck. Let them.",
  "Talent without work is just potential nobody pays for.",
  "Stop waiting for motivation. Discipline doesn't need a pep talk.",
  "Get up, suit up, show up, blow up. In that order.",
  "Your goals don't give a damn about your mood. Execute anyway.",
  "Average men want comfort. Rich men want the rep that scares them.",
  "Be obsessed or stay ordinary. There's no third option.",
  "Nobody writes legends about the man who played it safe.",
  "Sweat now or beg later. Pay the toll up front.",
  "The wolf that's hungry hunts harder than the wolf that's full. Stay hungry.",
  "Stack closes like ammo. You're going to war every single day.",
  "Talk less, close more. Let the commission check do the bragging.",
  "You don't find time to win. You take it from the men who won't.",
  "Excuses are the currency of the broke. Stop spending them.",
  "Show the market who runs it. Then go collect.",
  "Pain is rent for the body you want and the bank account you need.",
  "Do what the lazy won't so you live how they can't.",
  "The relentless always get paid. It's just a matter of when. Make it now.",
  "Your future is built in the hours nobody's clapping for.",
  "Hesitation is the most expensive habit you own. Drop it.",
  "Hunt the day before it hunts you and eats you alive.",
  "Chase two rabbits, catch nothing. Lock in on the kill.",
  "Standards over feelings. Hit the number when you feel like garbage.",
  "Make the calls you're scared of. That's where the rent money hides.",
  "You grow or you make excuses today. You can't do both.",
  "Be a problem for everyone who bet against you.",
  "Pick up the phone like your name's on the line. It is.",
  "Momentum is built, not handed out. Start swinging.",
  "You weren't born to be average. So quit acting broke.",
  "Greatness is a habit you build in private and cash in public.",
  "Bet on the man in the mirror. He's been overlooked long enough.",
  "Every rep you skip is a check you'll never cash.",
  "Be so good they have no choice but to pay you. Then get better.",
  "Win the morning, own the day, stack the decade.",
  "Fear is a compass pointing at the money. Run at it.",
  "The grind is undefeated. Stop fighting it and start using it.",
  "Your bank balance is a receipt for your discipline. Read it and grind.",
  "Make moves in silence. Let the closes scream.",
  "Comfort zones are where dreams go to rot. Get the hell out.",
  "Today's effort is tomorrow's lifestyle. Spend like a savage.",
  "Dominate the day or it dominates you. Pick fast.",
  "Get addicted to the process and the money chases you home.",
  "Soft choices, hard life. Hard choices, soft life. Choose hard.",
  "The only thing in your way is the man you were yesterday. Bury him.",
  "Hustle till your haters fill out an application.",
  "Closed mouths starve. Open yours and ask for the goddamn sale.",
  "Run your race so hard the field forgets they're in one.",
  "You're one phone call from a different life. Stop stalling. Make it.",
  "Get comfortable being uncomfortable or get comfortable being broke.",
  "Sharpen the axe, then swing it like the mortgage is due.",
  "Empires aren't built on good intentions. Build yours on dials.",
  "Be the storm. Stop being the guy waiting for it to pass.",
  "The only easy day was yesterday. Go earn this one.",
  "Beast mode isn't a mood. It's the bare minimum. Set it.",
  "Quit waiting for permission. Take the shot, take the money.",
  "Your potential is screaming and you keep hitting snooze. Wake up.",
  "Lions don't lose sleep over sheep. Hunt and ignore the noise.",
  "Do the work nobody sees so you live the life everybody wants.",
  "Today is a deposit on the man you're becoming. Max it out.",
  "Fortune favors the bold and laughs at the comfortable.",
  "Make the hard call first. The rest of the day kneels after that.",
  "Results or excuses. You can't carry both. Drop the dead weight.",
  "Grind in private, flex in public, repeat forever.",
  "The man who outworks everyone answers to no one.",
  "Don't count the dials. Make every dial count double.",
  "Stay hungry. Full men get lazy and lazy men get poor.",
  "Be a wrecking ball to your competition's quarter.",
  "Discipline today buys freedom you can't believe tomorrow.",
  "Win or learn, never lose. Then run it back twice as hard.",
  "Your name should sound like 'closer.' Go make it true.",
  "Quit waiting to feel ready. Ready is a thing you build mid-swing.",
  "Outlast, outwork, out-believe. That's the entire cheat code.",
  "Fill the calendar with kills, not coffee breaks.",
  "Be relentless on the days you want it the least. That's the whole secret.",
  "The market pays for courage. Bring a truckload today.",
  "Kill the easy task fast, then go hunt the one that scares you.",
  "Make excellence boring by doing it every single day without applause.",
  "Pressure's a privilege. Step in and perform or step off.",
  "You don't rise to goals, you fall to habits. Build savage ones.",
  "Burn the boats. The only way out is through and forward.",
  "Today's grind funds tomorrow's freedom. Clock the hell in.",
  "Be the man your goals require, not the boy your mood prefers.",
  "Speed plus reps equals money. Math doesn't lie. Move.",
  "The dip is where the soft quit. Push through and take their share.",
  "Make the day flinch. Hit it first, hit it hard, hit it again.",
  "Nobody's too busy for the dream that pays them. Get to work.",
  "You're built for this. Now go prove it before doubt does.",
  "Be too busy stacking wins to entertain a single excuse.",
  "Hard now, easy later. Soft now, sorry forever.",
  "The phone's a money printer. Quit staring and start pressing buttons.",
  "Stop managing your comfort and start manufacturing your fortune.",
  "Effort is the rent on the life you want. Pay it in full, daily.",
  "Be the guy who shows up when nobody's keeping score.",
  "Aim past comfortable. Then climb until your hands bleed.",
  "Hunt like you're starving, because comfort is one bad year away.",
  "The work is whispering your name. Answer it before someone else does.",
  "Greatness takes no days off. Match its schedule or lose to it.",
  "Make the call, eat the no, repeat until you're rich. It's that simple.",
  "Doubt has killed more fortunes than any market ever has. Move anyway.",
  "Be the exception. The average is overcrowded and underpaid.",
  "Today's undefeated until you decide to take it.",
  "Don't shrink to fit the room. Knock out a wall.",
  "Your grind is your signature. Sign it loud enough to deafen doubt.",
  "Get 1% better every day and watch a year make you unrecognizable.",
  "Hesitate and the deal walks to a man who didn't blink.",
  "Be unreasonable about the goal and ruthless with the clock.",
  "The only man you have to beat is the one you were yesterday. Beat him.",
  "Lift the iron, lift the phone. Both build the man and the money.",
  "Win the rep in front of you. The mountain handles itself.",
  "Make today expensive as hell for everyone betting against you.",
  "Stop waiting for the perfect moment. Strangle this one for everything it's got.",
  "The hard road is the only one that leads somewhere worth a damn.",
  "Be feared by your goals, not by your excuses.",
  "Every champion was a contender who flat refused to fold.",
  "Show up so consistently they have to call it luck to feel better.",
  "Action cures fear. So act, then act again before fear wakes up.",
  "The top's lonely because most won't climb. Good. Less traffic. Climb.",
  "Don't pray for an easy life. Pray for the strength to body a hard one.",
  "Money's just the scoreboard. Quit watching it and put points up.",
  "Be the storm the comfortable pray never reaches their door.",
  "Make the first hour brutal and the whole day bends the knee.",
  "Your comeback is built in the reps nobody's filming.",
  "Conquer the morning and the day raises a white flag.",
  "No half-reps, no half-days, no half-assed men. All in or all out.",
  "Get obsessed with the work and the rewards get obsessed with you.",
  "Be a closer in a world drowning in talkers.",
  "The phone won't ring itself. Make it ring with your wins.",
  "Tired isn't a reason. It's an excuse wearing a disguise.",
  "Run at the hard thing. The money's asleep on the other side of it.",
  "You don't need more time. You need more urgency and less Netflix.",
  "Every dial's a lottery ticket you actually control. Buy a thousand.",
  "Make your discipline louder than every distraction in your pocket.",
  "Win today and let tomorrow sweat about itself.",
  "Master the morning and you've already cornered the day.",
  "Be the reason your goals lose sleep at night.",
  "Stop building someone else's empire on company time. Build yours.",
  "Outhustle yesterday's you. That's the only rival that matters.",
  "Pain you choose makes you. Pain you dodge makes nothing.",
  "Dial like rent's overdue, because one bad month it will be.",
  "Be the hardest no to earn and the easiest yes to keep paying.",
  "The work is the prayer. Get on your knees and grind for it.",
  "Make the day so productive it pays you interest.",
  "Quit narrating the man you'll be. Go be that ruthless bastard now.",
  "Hungry men move faster. Stay starving for the next close.",
  "Be relentless in the hunt and gracious in the kill.",
  "Closers eat first. Elbow your way to the front of the line.",
  "The mountain won't move an inch. So you climb. Start now.",
  "Every legend stood exactly where you're standing. Then they moved.",
  "Be a machine while the rest are busy making excuses.",
  "Today you stack hard proof that you don't fold under fire.",
  "Make momentum your factory setting.",
  "The bold get bruised. The timid get nothing. Take the bruise.",
  "Win the boring days. That's the warehouse where empires hide.",
  "You're not behind. You're early to the work cowards refuse.",
  "Crush the call you've been ducking. Freedom's standing right behind it.",
  "Hard work is a magnet for luck. Get magnetic as hell.",
  "Be too disciplined to fail and too hungry to coast.",
  "The grind chose you. Choose it back, harder, every morning.",
  "Make the number, then go insult it with a bigger one.",
  "Be the man who turns pressure into paychecks on command.",
  "Your excuses bore me and they're boring your future too.",
  "Every closed door is just a hallway. Keep walking through.",
  "Strike first, strike hard, then follow up until they sign.",
  "The reps don't lie and they sure as hell don't take days off.",
  "Be feared by the lazy and respected by the great.",
  "Money flows to the man who moves with zero hesitation.",
  "Get up earlier than your problems and they never catch you.",
  "Make the impossible your warm-up set.",
  "The only real failure is the call you were too soft to make.",
  "Be a savage with the schedule and a gentleman with the win.",
  "Greatness is built on the days you didn't feel a thing for it.",
  "Stop waiting to get picked. Pick yourself and pick up the phone.",
  "Today belongs to whoever wants it most. Want it like rent's due.",
  "Be the closer the whole room slept on.",
  "Run the play till it prints, then run it twice as fast.",
  "Discipline is choosing what you want most over what you want right now.",
  "Make the mornings violent and the nights well-earned.",
  "The market bows to consistency. So be a goddamn metronome.",
  "Hustle now so your bloodline never has to.",
  "Be the man who finishes the thing that scared everyone else off.",
  "One call can flip the whole month. Treat every one like the one.",
  "Sharpen your edge daily or the competition files it down.",
  "Don't manage the day. Take it by the throat.",
  "Be relentless. Relentless always, always cashes the check.",
  "Your habits are voting on your future. Vote like a killer.",
  "Get loud with the work, dead silent with the complaints.",
  "The grind is the gift nobody asked for and everyone needs. Open it.",
  "Be the standard, not the apology for falling short of it.",
  "Today's discomfort is next year's flex. Go earn the flex.",
  "Make the call that makes the whole damn month.",
  "Win the reps nobody's counting and watch the world start counting you.",
  "Be a problem the market can only fix by paying you stupid money.",
  "Fortune punishes the hesitant on sight. Move with intent.",
  "Outlast the dip and the doubters. They quit at the same exit.",
  "The phone is your sword. Swing it from open to close.",
  "Get addicted to the climb, allergic to the couch.",
  "Be the man who shows up first and gets dragged out last.",
  "Make the hard thing your signature move.",
  "Today you out-dial, out-work, and out-believe every soft man alive.",
  "Stop renting your hours to fear. Own every minute.",
  "Be the kind of busy that quietly builds an empire.",
  "Every great run starts with one brutal step. Take it before you think.",
  "Sweat is just weakness leaving the body on commission.",
  "Be the closer who never blinks and never apologizes for winning.",
  "Hunt today like the freezer's bone empty.",
  "The reps compound into freedom. Stack them like a maniac.",
  "Be unbothered by no and unstoppable toward yes.",
  "Make discipline your religion and the close your prayer.",
  "Today's a weapon. Point it straight at the goal and fire.",
  "The grind owes you nothing, but it always pays the obsessed.",
  "Be a force of nature, not a weather forecast.",
  "Make the calls until the calls make you untouchable.",
  "You're built for the hard road. Stop window-shopping the easy one.",
  "Out-effort your excuses before breakfast.",
  "Be the man your goals can't outrun no matter how fast they sprint.",
  "Pressure on the bold is just rocket fuel. Light it.",
  "Don't wait on opportunity. Strangle it into existence.",
  "Win the dial in front of you and the day follows like a dog.",
  "Be relentless when it's boring. The boring days build billionaires.",
  "Every problem is a sale wearing a disguise. Close it.",
  "Make the work non-negotiable and the wins become inevitable.",
  "Today the lazy lose ground. Annex it.",
  "Be too locked in to be lucky and too disciplined to be denied.",
  "Hunger beats talent that got fat and comfortable.",
  "Get up and get after it before the world gets a chance to say no.",
  "Be a savage on the phone and a king when you walk in the door.",
  "Make every hour answer directly to your ambition.",
  "The grind is the price tag on the man you want to be. Pay it cash.",
  "Be the comeback nobody had the stomach to bet on.",
  "Run it back harder every single morning until they retire the record.",
  "Closers don't have bad days. They have tuition.",
  "Make the dial, make the day, make the year, make the name.",
  "Be obsessed enough to terrify the man you used to be.",
  "Today's built for men who refuse to fold under any hand.",
  "Outwork the room and let the scoreboard do the explaining.",
  "Be the hardest worker and the easiest man to bet on.",
  "The phone's only heavy to men too soft to lift it.",
  "Make your discipline the loudest thing in the building.",
  "Stop circling the work. Land on it and break its neck.",
  "Be relentless, be ready, be paid in full.",
  "The man who keeps dialing keeps eating. Keep dialing.",
  "Make today a flex your future self brags about at the top.",
  "Hunt the scary call first and the rest of the day turns to butter.",
  "Be too busy building to give doubt a chair.",
  "Greatness is reps plus refusal to quit. Bring both, all day.",
  "Today you set the pace. Make it brutal enough to break the field.",
  "Be the wolf, never the worry.",
  "Every dial's a brick. Lay enough and you're staring at a palace.",
  "Don't ask if you can. Decide that you will and go collect.",
  "Make the grind your home turf and watch everyone else slip.",
  "Be relentless when the scoreboard's spitting on you.",
  "The market respects effort. Show it some it can't ignore.",
  "Outhustle the version of you that wanted to take it easy.",
  "Be a closer in a world full of maybes and someday-soons.",
  "Today you earn the right to win tomorrow. Pay up front.",
  "Make the call that flips the whole story in your favor.",
  "Be the man who never needs a reason to go to work.",
  "Pressure builds you or buries you. Choose built, every time.",
  "Get loud with results, mute the excuses entirely.",
  "Be the reason the leaderboard needs a taller top.",
  "Run the day like a man with everything to prove and nothing to lose.",
  "The grind doesn't negotiate. Stop trying and start grinding.",
  "Make discomfort a daily appointment you never reschedule.",
  "Be relentless until relentless starts looking like destiny.",
  "Today the dials decide your year. Make every one a statement.",
  "Hunt, close, repeat. That's the whole gospel.",
  "Be the standard the rest measure themselves against and fall short of.",
  "Make the first call before fear even finds its shoes.",
  "The man on a mission moves long before he feels ready.",
  "Be too disciplined to drift and too hungry to settle.",
  "Outwork the doubt right out of your own skull.",
  "Today you stack proof you were cut from rarer cloth.",
  "Be a savage with the schedule and merciless with the excuses.",
  "Make the grind a habit and the wins a boring routine.",
  "The phone rewards the brave and ignores the rest. Be brave all day.",
  "Be the man who turns Mondays into momentum and momentum into money.",
  "Hunt the day with everything in the tank and then find more.",
  "Make discipline so normal it feels like breathing.",
  "Be relentless, ruthless with time, and rich because of it.",
  "Today you out-dial yesterday or you stood still wearing nice shoes.",
  "Be the closer the market can't shake loose no matter how hard it tries.",
  "Make the hard yes your favorite sound in the world.",
  "The grind is the gym for your future. Show up and get strong.",
  "Be too hungry to settle and too sharp to quit.",
  "Win the morning reps and the whole day signs over the deed.",
  "Make every no a deposit on the yes that changes everything.",
  "Be the man who answers the call to greatness before it stops ringing.",
  "Today's effort writes tomorrow's headline. Make it impossible to ignore.",
  "Hunt like a closer, recover like a champion, repeat like a machine.",
  "Be relentless on the dead-quiet Tuesdays nobody's watching.",
  "Make the work your weapon and the day your hunting ground.",
  "The empire goes up one dial at a time. Lay the next brick.",
  "Be the storm the comfortable never live through.",
  "Today you choose hard, and hard quietly chooses the winners.",
  "Make the calls your competition's too soft to even attempt.",
  "Be the man whose discipline makes his own doubts embarrassed.",
  "Run at the goal until the goal runs out of room to hide.",
  "Be relentless and let relentless foot the entire bill.",
  "Make today the day the market finally learns your name and fears it.",
  "Hunt now. Rest when the goal's bleeding out on the floor.",
  "Be the closer, the grinder, the standard. Be all three before noon.",
  "Out-work the world and let the bank account explain the rest.",
  "Make discipline your default and success your permanent shadow.",
  "Be the man who refuses to let a single hard day win.",
  "Today you build the legend one merciless rep at a time.",
  "Hunt the call, eat the no, stack the yes, count the money.",
  "Be relentless until your goals are the ones begging for mercy.",
  "Make the grind beautiful by never once skipping it.",
  "The phone is the path to everything you want. Walk it all day.",
  "Be too locked in to lose and too hungry to quit.",
  "Make every minute a down payment on the dream they said you couldn't have.",
  "Hunt hard, close clean, repeat forever, retire rich.",
  "Be the man your future is on its knees begging you to become. Today.",
  "Set the tone or spend the day dancing to someone else's.",
  "Be the guy who dials while everyone else is busy doubting.",
  "Make the hard call your first call, every single morning.",
  "Win the rep, win the hour, win the war, take the spoils.",
  "Be relentless when the room goes dead quiet.",
  "Your work ethic is your reputation. Build a violent one.",
  "Out-grind yesterday and the future bends over backward for you.",
  "Be the man who turns rejection into straight rocket fuel.",
  "Make the dials until the doubt taps out and crawls home.",
  "Discipline carries you long after motivation clocks out drunk.",
  "Be the closer who treats every call like it's the one that pays for the house.",
  "Today the soft fold. Be the man who physically cannot.",
  "Make excellence your floor, not your ceiling.",
  "Hunt the day before your alarm even finishes screaming.",
  "Be relentless, be starving, be the one they study at the top.",
  "The grind separates men from intentions. Pick up the phone and prove which you are.",
  "Make your name a verb that means 'always closes.'",
  "Be unreasonable today. Reasonable men die broke and on time.",
  "Out-work the talented and out-last the lucky. They both fade.",
  "Every yes is buried under a pile of no's. Grab a shovel.",
  "Be the storm, the standard, and the competition's worst nightmare.",
  "Make today a clinic on refusing to fucking quit.",
  "Hunt like the comeback depends on it. Spoiler: it does.",
  "Be too busy closing to keep count of the no's.",
  "Discipline now, deals all year, freedom for life.",
  "Be the man who makes hard look effortless by doing it daily.",
  "Run the day so hard it remembers your name and warns the next one.",
  "Make the call, take the swing, own the outcome, no matter what.",
  "Be relentless until relentless is just your resting face.",
  "Win the dial, win the deal, win the decade, own the game.",
  "Be the hardest worker, the coldest closer, the last man standing.",
  "Make the grind your love language and the money your dialect.",
  "Hunt today. The freezer fills itself for exactly nobody.",
  "Be the man your goals can't outrun, outlast, or out-hustle.",
  "Today you build the proof. Tomorrow you cash it in.",
];

/** Today's hype line (stable per calendar day, rotates yearly). */
export function todaysHype(): string {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((now.getTime() - start.getTime()) / 86400000);
  return HYPE_LINES[dayOfYear % HYPE_LINES.length];
}
