/**
 * Daily hype line for the dashboard. One per day of the year (stable per day),
 * so it changes every morning. A blend: Goggins grit, Tate money/masculine,
 * Belfort closing, the real why (rich, family, the lifestyle), and faith /
 * self-alignment (God, infinite intelligence, you will do great today).
 * Personal dashboard — unfiltered by design.
 */
export const HYPE_LINES: string[] = [
  "Get up. Nobody's coming to do this for you, and thank God, because it's yours.",
  "Pick up the fucking phone. Every dial is a brick in your family's house.",
  "You will do great today. Now go make the universe agree with you.",
  "Stay hard. The dream doesn't care that you're tired.",
  "God gave you this fire. Don't insult Him by sitting on it.",
  "Broke is temporary if you work. Lazy is the only thing that's permanent.",
  "Close them today so your mom never sees another bill she can't pay.",
  "You're plugged into infinite intelligence. Use it and out-think the room.",
  "The car, the house, the freedom — all of it is on the other side of these calls.",
  "Discipline is just love for your future self. Show some.",
  "Nobody's harder on you than you. Good. Channel it and go get rich.",
  "Speed. Money rewards the man who moves before he's ready.",
  "You were built for more than comfort. Prove it before noon.",
  "Get rich so your kids inherit options instead of struggle.",
  "The phone weighs two ounces. Your excuses weigh a ton. Drop the excuses.",
  "Align with the highest version of you, then go act exactly like him.",
  "Callus your mind. The no's stop hurting once you stop being soft.",
  "Pray, then dial. Faith without work is just a wish.",
  "You are powerful. You connect to God and the work tunes the signal.",
  "Today you out-work the man you were yesterday or you stay him.",
  "Scared money stays broke. Bet on yourself like you mean it.",
  "Make the money so the people you love never have to think about it again.",
  "The grind is a prayer. Get on your knees and put in the reps.",
  "You will not be average. That ends the second you start dialing.",
  "Models, mansions, machines — they live behind a wall of dials. Start climbing.",
  "God doesn't bless the comfortable. He blesses the man who moves.",
  "Get up earlier than your problems and they'll never catch you.",
  "Win today. Then go home and look your family in the eye like a man who delivered.",
  "Your potential is a debt you owe God. Pay it down today.",
  "Hard work beats talent that's busy making excuses. Out-work all of them.",
  "Close like rent is due, because someday it will be and you'll be glad you trained.",
  "You're not behind. You're early to the work the soft refuse to do.",
  "Talk to God in the morning, talk to the market all afternoon, count it at night.",
  "Be obsessed. Obsession is just discipline that finally fell in love with the goal.",
  "The freedom to never ask anyone for anything — that's what these calls buy.",
  "Stay in the fight. Quitters don't get the car, the house, or the peace.",
  "You have infinite intelligence on tap. Stop drinking from the puddle of doubt.",
  "Get rich quietly. Let the lifestyle do the talking later.",
  "Today is a gift. Most men waste it. You're not most men.",
  "Make the call you're scared of. That's exactly where the money's hiding.",
  "God put a champion in you. Stop feeding him excuses and feed him reps.",
  "One more dial. That's the whole secret. Always one more.",
  "Build the life so good your future self sends a thank-you note back in time.",
  "Comfort is the enemy. Run at the hard thing and let it forge you.",
  "You will do great today because you decided to, not because you felt like it.",
  "Stack closes like a man building an empire one brick at a time. Because you are.",
  "Get the bag so your family's struggle dies with this generation.",
  "Discipline today, freedom tomorrow, legacy forever. Pay the toll.",
  "The man who outworks everyone answers to no one. Be him.",
  "You're a vessel for something bigger. Pour it into the work.",
  "Don't pray for an easy life. Pray for the strength to crush a hard one.",
  "Every no is tuition. Every yes is graduation. Keep enrolling.",
  "Get rich so the word 'no' loses all its power over your life.",
  "Mediocrity is a daily choice. Choose violence on your potential instead.",
  "God, the grind, and the goal. Line them up and become unstoppable.",
  "You are capable of more than you've ever shown. Today's the audition.",
  "Make the calls until the calls make you the man you're meant to be.",
  "Win the morning and the day surrenders without a fight.",
  "The car you want is just a number of closes. Go do the math with your hands.",
  "Stay hard when it's boring. The boring days are where empires get built.",
  "You connect to infinite intelligence. Doubt is a bad connection. Hang up on it.",
  "Get up and get after it before the world tells you you can't.",
  "Provide so well your family never knows what 'tight month' means.",
  "Faith moves mountains. Effort moves the needle. Bring both today.",
  "You don't rise to your goals. You fall to your habits. So build savage ones.",
  "Be a closer in a world drowning in talkers and excuse-makers.",
  "God didn't give you this dream to watch you fold. Show up.",
  "Money loves speed and hates hesitation. Pick a side and move.",
  "The peace of never worrying about money is worth every brutal morning.",
  "You will do great today. Say it, mean it, then make it true with work.",
  "Hunger beats talent that got comfortable and full. Stay starving.",
  "Get rich so you can be generous on a scale that actually changes lives.",
  "Discipline is choosing what you want most over what you want right now.",
  "You are powerful, you are chosen, you are capable. Now go act like it.",
  "Make today expensive for everyone who bet against you.",
  "Pray for the courage to make the hard call, then make twenty of them.",
  "The lifestyle you want is real and it's earned, never given. Earn it.",
  "Stay hard. Soft men don't build, don't provide, don't lead.",
  "Tap into the source. You were made to create, so create your fortune.",
  "Get up. The version of you that wins is already awake and waiting.",
  "Close the deal that pays for the trip you'll take your family on.",
  "God blesses effort, not intentions. Bring the effort.",
  "You're one phone call away from a completely different life. Make it.",
  "Out-work your doubt. It can't keep pace with a man on a mission from God.",
  "Get rich so 'someday' becomes 'done.'",
  "The grind doesn't ask how you feel. Clock in and become great anyway.",
  "You have the mind of a champion and a line to the infinite. Use both today.",
  "Make the money. Buy the freedom. Keep the faith. In that order, forever.",
  "Stay hard when the scoreboard's against you. That's when men are made.",
  "Today you build proof you were never meant to be ordinary.",
  "Get up, suit up, plug into God, and go take what's yours.",
  "The house with no mortgage is a number of yeses away. Go collect them.",
  "Discipline now so your bloodline lives easy later.",
  "You are a creator, not a victim. Create a brutal, beautiful day.",
  "Pick up the phone like your name and your God are on the line. They are.",
  "Get rich so you can fund the dreams of people who can't fund their own.",
  "Stay relentless. The relentless always cash out eventually. Make it today.",
  "Your future is built in the hours nobody claps for. Build it.",
  "Move with faith and ferocity. That combination is undefeated.",
  "Win the rep in front of you and let God handle the mountain.",
  "Get the car, the house, the freedom — but get the man first. Become him today.",
  "You will do great today. Doubt is just static. Tune to the work.",
  "Hard now, easy later. Soft now, sorry forever. Choose hard.",
  "Make the calls that make the month that makes the year that frees your family.",
  "Stay hard. Champions are just men who refused to negotiate with their weakness.",
  "Plug into infinite intelligence and out-think every problem in your path.",
  "Get up and grind like the life you want is watching. It is.",
  "Provide, protect, perform. That's the job. Do it like a king today.",
  "God put the resource in you. The work is how you withdraw it.",
  "One brutal hour up front and the whole day bows to you.",
  "Get rich so you never have to choose between time with family and the bills.",
  "Be unreasonable about the goal and ruthless with the clock.",
  "You are powerful beyond your excuses. Today you finally act like it.",
  "Close them. Every signature is a step toward the life you swore you'd build.",
  "Stay hard when it's quiet. Discipline is loudest when nobody's watching.",
  "Connect to the source, then dominate the source's competition.",
  "Get up. The money doesn't sleep and neither does your competition. Move.",
  "Make today a deposit on the man God's calling you to become.",
  "The dream car is just discipline with a paint job. Go earn it.",
  "Pray hard, work harder, give the hardest. That's the whole life.",
  "You will do great today because greatness is a decision and you just made it.",
  "Hunt the hard call first. The rest of the day turns soft after that.",
  "Get rich so your mom retires and your dad finally rests.",
  "Stay relentless until relentless looks like destiny to everyone else.",
  "You're built different. Today you stop saying it and start showing it.",
  "Faith is the fuel, work is the engine. Floor it.",
  "Make the man who quits and the man who wins both live in you. Then feed the right one.",
  "Get the bag, keep the soul. You can have both if you stay aligned.",
  "Stay hard. The boats won't carry themselves. Who's gonna carry them? You.",
  "Plug in. You have access to infinite intelligence and a hard limit on excuses.",
  "Get up and out-work the doubt before it has coffee.",
  "Provide so completely your family never learns the word 'sacrifice' the hard way.",
  "God honors the bold. Go be bold all day.",
  "Win the dial, win the deal, win the decade, build the dynasty.",
  "The lifestyle is downstream of the discipline. Go upstream and stay there.",
  "You will do great today. Now stop reading and go fucking prove it.",
  "Stay hard when you're losing. Losing is just winning that hasn't finished cooking.",
  "Tap the source, swing the phone, count the money, thank God. Repeat.",
  "Get up earlier, want it harder, work it longer. That's the edge.",
  "Make the money quietly and let the freedom announce itself.",
  "Discipline is a love language. Speak it to your future today.",
  "You are powerful, chosen, and capable. The work is how you remember it.",
  "Close the deal that buys back your father's old age.",
  "Stay hard. Comfort never built a man worth following.",
  "Connect to God in the morning so you can connect with closers all day.",
  "Get rich so generosity becomes a habit, not a stretch.",
  "The grind separates men from wishes. Pick up the phone and prove what you are.",
  "You will do great today because you trained for exactly this.",
  "Hunt like the freezer's empty and the family's counting on you. They are.",
  "Stay relentless on the boring days. That's where the fortune actually hides.",
  "Plug into the infinite and dial like a man who already knows he wins.",
  "Get up. Mediocrity is comfortable and it's a trap. Burn it down.",
  "Provide like a king, work like a soldier, pray like a son.",
  "God's not impressed by potential. He's impressed by the man who uses it.",
  "Make the call that makes the month. Then go make ten more.",
  "The dream house has a price tag and it's paid in dials. Start paying.",
  "Discipline today, freedom tomorrow, blessing for generations.",
  "You're a creator with a line to the infinite. Create your fortune today.",
  "Stay hard. The man who can't be broken can't be stopped.",
  "Get rich so 'I can't afford it' permanently leaves your family's vocabulary.",
  "Out-work the room and let the bank account explain why.",
  "Pray for strength, not an easy road. Then go walk the hard one like a man.",
  "You will do great today. The work is just you proving God right.",
  "Close them. Each yes is another wall in the life you're building.",
  "Stay relentless. Soft men quit at the exact mile where it gets good.",
  "Tap the source, trust the grind, take the win.",
  "Get up and become the man your family brags about.",
  "The car, the house, the freedom — they're real, they're earned, go get them.",
  "Discipline is just remembering you're built for more than this. Act on it.",
  "You are powerful because you're connected to something infinite. Plug in and grind.",
  "Make today violent on your goals and gentle with your faith.",
  "Close the deal that puts your kids in a better school than you had.",
  "Stay hard. The hardest worker in the room fears no one in it.",
  "Connect, create, close. That's the whole ministry of a hustler.",
  "Get rich so your 'no' carries weight and your 'yes' changes lives.",
  "The grind is undefeated. Stop fighting it and start riding it.",
  "You will do great today because you refuse to do anything less.",
  "Hunt the day with everything you've got, then dig up more.",
  "Stay relentless until your goals are the ones begging for mercy.",
  "Plug into infinite intelligence and out-hustle every doubter alive.",
  "Get up. The man you want to be is built in the next eight hours. Build him.",
  "Provide so well your family forgets what fear of money even felt like.",
  "God gave you the talent. The dials are how you say thank you.",
  "One more call. That's all greatness ever asks. Always one more.",
  "The freedom to live on your terms is the only luxury worth grinding for. Grind.",
  "Discipline now so 'broke' becomes a story you tell, not a place you live.",
  "You're a vessel for greatness. Stop leaking it into excuses.",
  "Stay hard when motivation's gone. Discipline doesn't need a pep talk.",
  "Get rich and stay humble. The source giveth and the ego taketh away.",
  "Make the call. Eat the no. Thank God. Repeat until you're free.",
  "You will do great today. Now go make it impossible to argue with.",
  "Hunt like a closer, recover like a champion, pray like a son, repeat.",
  "Stay relentless on the dead-quiet days nobody's watching.",
  "Tap the infinite, swing the phone, build the dynasty.",
  "Get up before your alarm and outwork the man who hit snooze.",
  "Provide, protect, perform, then go to bed empty because you left it all out there.",
  "God blesses the grinder. Go give Him something to bless.",
  "Win the morning reps and the whole day signs the deed over to you.",
  "The lifestyle you want is a number. Go make the number with your hands.",
  "Discipline is the bridge between the prayer and the answer. Walk it.",
  "You are powerful, capable, chosen. The work is your proof of receipt.",
  "Close the deal that lets your wife stop worrying for good.",
  "Stay hard. The men who built everything were tired too. They moved anyway.",
  "Plug into the source and become a problem the market can't solve cheaply.",
  "Get rich so your time becomes yours and you spend it on the people you love.",
  "Move with faith and ferocity. That's how kingdoms get built.",
  "You will do great today because you trained your mind to leave you no choice.",
  "Hunt the no's. Each one is one dial closer to the yes that changes the year.",
  "Stay relentless. The relentless are the only ones still standing at the top.",
  "Tap the infinite intelligence in you and out-think the whole damn field.",
  "Get up. Comfort is a thief. Go take your hours back and turn them to gold.",
  "Provide like the man God made you to be. Soft is not in the job description.",
  "Faith without work is dead. So is the dream you won't grind for. Move.",
  "Make today a clinic on refusing to quit when it gets ugly.",
  "Get the bag, build the house, free the family, keep the faith. That's the mission.",
  "Stay hard. Who carries the dream when it gets heavy? You do. Always you.",
  "Plug in, lock in, cash in. In that exact order, every morning.",
  "Get up and out-work the doubt before it finds its shoes.",
  "Provide so generously that giving becomes the family business.",
  "God honors the man who shows up scared and dials anyway. Be him.",
  "Win the dial. Win the deal. Win the day. Win the life. One rep at a time.",
  "The dream is paid for in discipline. Make today's installment.",
  "You will do great today. Stop negotiating with the part of you that wants to nap.",
  "Stay relentless when you're behind. That's the only place comebacks are born.",
  "Tap the source, trust the grind, take what was always meant for you.",
  "Get up. The man who provides, protects, and prays leaves nothing on the table.",
  "Provide a life so good your kids grow up thinking it was always easy.",
  "God didn't make you to be small. Take up space with your work today.",
  "Make the call that makes the month and changes the trajectory.",
  "The freedom car, the paid-off house, the easy holidays — go fund them today.",
  "Discipline today is the down payment on every blessing you're chasing.",
  "You are a creator wired to the infinite. Go create an unforgettable day.",
  "Stay hard. The grind humbles the soft and crowns the relentless.",
  "Get rich so 'I'll handle it' becomes the truest thing you ever say.",
  "Out-work yesterday's you. He's the only opponent that's ever mattered.",
  "Pray it, plan it, then go fucking execute it. Faith plus reps.",
  "You will do great today because greatness is a habit and you've been training.",
  "Close them. Every signature buys back a piece of your freedom.",
  "Stay relentless. Soft men cash out their dreams for comfort. Don't trade.",
  "Tap the infinite, swing the phone, fund the dream, thank the source.",
  "Get up and become the answer to your family's prayers.",
  "The lifestyle is real and it's earned. Go earn it like a man who believes.",
  "Discipline is love for the people counting on you. Show it in reps.",
  "You are powerful because you plug into something bigger than fear. Plug in.",
  "Make today brutal on your goals and faithful to your purpose.",
  "Close the deal that takes the weight off your father's shoulders for good.",
  "Stay hard. The man who can't be broken can't be denied.",
  "Connect, create, close, repeat. That's the rhythm of a man who wins.",
  "Get rich so your generosity outlives you.",
  "The grind is undefeated and it's on your side the moment you show up. Show up.",
  "You will do great today because you decided to stop being almost great.",
  "Hunt the day like it owes you, then collect with both hands.",
  "Stay relentless until the doubters apply to work for you.",
  "Plug into infinite intelligence and out-hustle the man you were last year.",
  "Get up. The next eight hours either build the dream or excuse it. Build.",
  "Provide so completely your family's struggle ends with your generation. Period.",
  "God gave you the hunger. The dials are how you honor it.",
  "One more call. The whole empire is hiding in 'one more.' Always one more.",
  "The freedom to never explain yourself to a boss again — grind for that.",
  "Discipline now so the word 'broke' becomes a memory, not a forecast.",
  "You're a vessel built for greatness. Stop pouring it out as excuses.",
  "Stay hard when it's boring, lonely, and thankless. That's the forge.",
  "Get rich, stay grounded. The source gives and the ego forgets who gave.",
  "Make the call, eat the no, keep the faith, count the wins.",
  "You will do great today. Now close the laptop and go make it undeniable.",
  "Hunt like a closer, grind like a soldier, walk like a son of the most high.",
  "Stay relentless on the silent Tuesdays. Empires are built on Tuesdays.",
  "Tap the infinite, swing the phone, build the legacy your name deserves.",
  "Get up earlier, hunger harder, grind longer. That's the only edge there is.",
  "Provide, protect, perform, then rest empty, knowing you gave it everything.",
  "God blesses the bold and ignores the timid. Go be impossible to ignore.",
  "Win the morning, win the man, and the money has no choice but to follow.",
  "The lifestyle you want is downstream of who you become. Become him today.",
  "Discipline is the prayer that moves your own hands. Pray with action.",
  "You are powerful, chosen, capable, connected. The reps are how you cash it in.",
  "Close the deal that buys your family the time you never got with yours.",
  "Stay hard. The comfortable die with their music still in them. Not you.",
  "Plug into the source and become the storm the soft never survive.",
  "Get rich so you can be the reason somebody else's family makes it.",
  "Move with faith, work like a savage, give like a king. That's the whole code.",
  "You will do great today because you trained your mind to accept nothing less.",
  "Hunt the no's like a man who knows the yes is right behind the next one.",
  "Stay relentless. The last man dialing is the first man paid.",
  "Tap your infinite intelligence and outsmart every obstacle in the path.",
  "Get up. Comfort robbed enough of your mornings. Take this one back.",
  "Provide a future your kids will spend their lives grateful for.",
  "Faith fuels it, discipline drives it, the dials deliver it. Go.",
  "Make today a war you win and a prayer you keep.",
  "Get the bag, build the house, free your people, glorify the source.",
  "Stay hard. The dream's heavy. You were built to carry heavy. Carry it.",
  "Plug in, grind out, cash in, give back. The full circle of a real man.",
  "Get up and out-work the man who's hungry for your spot. He's out there.",
  "Provide so well that 'we can't' dies in your house forever.",
  "God put a closer in you. Stop starving him with doubt. Feed him dials.",
  "Win the dial, win the deal, win the year, build the dynasty, keep the faith.",
  "The dream's paid for in reps. Pay today's like it's the one that matters. It is.",
  "You will do great today. Now go close like your whole bloodline is watching.",
  "Get up. The grind is calling and so is God. Answer both.",
  "Make the money, free the family, fund the dream, thank the source.",
  "Stay hard when you want to quit. That want is the test. Pass it.",
  "You're connected to the infinite. Act like a man who knows it.",
  "Close the deal that buys your mother the house she pointed at years ago.",
  "Discipline is the rent for the man you're becoming. Pay it daily.",
  "Get rich so your time belongs to you and the people you love.",
  "Out-work the doubt, out-last the lazy, out-pray the proud.",
  "You will do great today. Now make the next hour brutal.",
  "Hunt the call you're avoiding. The breakthrough's standing behind it.",
  "Stay relentless. The man who keeps dialing keeps eating.",
  "Plug into the source and become unrecognizable by next year.",
  "Get up and go earn the lifestyle you keep daydreaming about.",
  "Provide so completely your family forgets what worry tasted like.",
  "God blesses motion. Stop praying for the answer and go be it.",
  "One more dial. The whole life flips on 'one more.' Always.",
  "The freedom you want is on the other side of work you're avoiding. Go.",
  "Discipline today, blessings tomorrow, legacy for the bloodline.",
  "You are powerful. You are capable. You are chosen. Now go grind like it.",
  "Make today expensive for your doubts and generous for your future.",
  "Close them. Each yes is a brick in the house no one can take from you.",
  "Stay hard. Soft men inherit regret. Hard men build dynasties.",
  "Tap the infinite, swing the phone, change the family tree.",
  "Get up before the world says no, and dial until it says yes.",
  "Provide like a king, hustle like a soldier, kneel like a son.",
  "Faith and ferocity. Bring both and watch what the day becomes.",
  "Win the rep, trust the source, take the win, repeat forever.",
  "The car, the house, the freedom — earned, never given. Earn it today.",
  "You will do great today because you stopped giving yourself a choice.",
  "Hunt the day. The man who provides doesn't wait to feel ready.",
  "Stay relentless until 'no' loses every ounce of its power over you.",
  "Plug in and out-think every problem the market throws at you.",
  "Get rich so generosity becomes your reflex, not your stretch.",
  "Discipline is love made visible. Show it in reps your family will feel.",
  "You're a vessel for greatness. Don't waste it on comfort. Pour it out.",
  "Make the call that frees a future you can't even picture yet.",
  "Stay hard. The boats are heavy. You were built for heavy. Carry them.",
  "Connect to God, close with conviction, count it with gratitude.",
  "Get up and become the answer your family's been praying for.",
  "The lifestyle is a number and the number is dials. Go do the math.",
  "Faith fuels the fire, discipline feeds it, the phone spreads it. Move.",
  "You will do great today. Now stop reading and go make it real.",
  "Hunt the no's like a man who knows the yes is close. Because it is.",
  "Stay relentless on the quiet days. That's where the fortune sleeps.",
  "Plug into infinite intelligence and outwork the man you used to be.",
  "Get rich so your kids start the race ten laps ahead of where you did.",
  "Discipline now so freedom isn't a fantasy, it's a Tuesday.",
  "You are powerful beyond your fear. Today you finally act like it.",
  "Make today a war on mediocrity and a prayer of pure gratitude.",
  "Close the deal that lets your dad finally put his tools down.",
  "Stay hard. Champions are men who refused to quit when it counted.",
  "Tap the source, swing the phone, build the dynasty, keep the faith.",
  "Get up and out-hunger the man trying to take your spot.",
  "Provide so well that struggle becomes a story, never a season.",
  "God gave you the dream and the strength. The dials are the bridge. Cross it.",
  "Win the dial, win the deal, win the decade, glorify the source.",
  "The freedom to never beg for anything is worth every brutal morning.",
  "You will do great today. Now go close like the rent's due and God's watching.",
  "Get up. The lazy version of you doesn't get the car, the house, or the peace.",
  "Make the money so quiet the lifestyle does all the talking later.",
  "Stay relentless. Soft men trade dreams for comfort. You don't trade.",
  "Plug in, lock in, cash in, give back. The full loop of a real one.",
  "Get rich and stay humble. The source gives; the grateful keep getting.",
  "Discipline is the prayer that moves your own two hands. Pray with them.",
  "You're connected to the infinite and capped only by your excuses. Drop them.",
  "Make today the day your future self thanks God you didn't quit.",
  "Hunt hard, close clean, provide fully, pray daily. That's the whole life.",
  "Get up. You were built for this exact day. Go prove it before noon.",
  "Stay hard, stay hungry, stay faithful. The rest takes care of itself.",
];

/** Today's hype line (stable per calendar day, rotates yearly). */
export function todaysHype(): string {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((now.getTime() - start.getTime()) / 86400000);
  return HYPE_LINES[dayOfYear % HYPE_LINES.length];
}
