/**
 * Daily hype line for the dashboard. One per day of the year (stable per day),
 * so it changes every morning. Sales-warrior, go-get-'em energy.
 */
export const HYPE_LINES: string[] = [
  "Wake up and dominate. Nobody's coming to do it for you.",
  "Every no is a step closer to the yes that changes your year.",
  "The phone weighs two ounces. Pick it up and get rich.",
  "Discipline is just remembering what you actually want.",
  "You're not tired, you're undecided. Decide, then move.",
  "Champions don't wait for motivation. They build it with reps.",
  "Today the market finds out you showed up. Make it hurt.",
  "Comfort is a slow death. Go do the hard thing first.",
  "Outwork your doubt. It can't keep up with a man on a mission.",
  "Money loves speed. Stop thinking, start dialing.",
  "Your competition is still asleep. Steal the morning.",
  "Pressure makes diamonds. Apply it to yourself daily.",
  "The grind doesn't care how you feel. Show up anyway.",
  "Be the guy they can't ignore. Loud results, quiet ego.",
  "One more dial. That's the whole game. Always one more.",
  "Scared money don't make money. Bet on yourself today.",
  "You eat what you kill. Go hunting.",
  "Make today so good your future self sends a thank-you note.",
  "Winners are just losers who refused to quit. Refuse.",
  "Stop negotiating with the version of you that wants to nap.",
  "Hard work beats talent when talent won't pick up the phone.",
  "The dream is free. The hustle is sold separately.",
  "Get up. Suit up. Show up. Blow up.",
  "Your goals don't care about your mood. Execute.",
  "Average is a choice. Choose violence on your potential.",
  "Be obsessed or be ordinary. Pick one and live it.",
  "Nobody remembers the man who played it safe.",
  "Sweat now or stress later. Pay the price up front.",
  "The wolf on the hill is hungrier than the wolf on top.",
  "Stack small wins until they become an empire.",
  "Talk less, close more. Let the numbers brag for you.",
  "You don't find time to win. You make it and defend it.",
  "Excuses are the language of the broke. Speak money instead.",
  "Show the market who runs this. Spoiler: it's you.",
  "Pain is temporary. Quitting lasts forever. Keep going.",
  "Do today what others won't, so you live like others can't.",
  "Be relentless. The relentless always get paid eventually.",
  "Your future is built in the hours nobody claps for.",
  "Hesitation is expensive. Action is free. Choose action.",
  "Hunt the day before it hunts you.",
  "The man who chases two rabbits catches none. Lock in.",
  "Standards over feelings. Hit the number regardless.",
  "Make the calls you're afraid of. That's where the money hides.",
  "Today you either grow or you make excuses. Not both.",
  "Be the hardest worker in every room you enter.",
  "Pick up the phone like your legacy depends on it. It does.",
  "Momentum is built, not found. Start now and don't stop.",
  "You were not born to be average. Act like it today.",
  "Greatness is a habit, not a moment. Build the habit.",
  "Bet on the man in the mirror. He's been underrated long enough.",
  "The reps you skip are the wins you'll never see.",
  "Be so good they have to pay you. Then get better.",
  "Win the morning, own the day, stack the year.",
  "Fear is a compass. Run toward what scares you.",
  "The grind is undefeated. Join its side.",
  "Your bank account reflects your discipline. Audit it daily.",
  "Make moves in silence and let the closes do the talking.",
  "Comfort zones are where dreams go to die. Get out.",
  "Today's effort is tomorrow's lifestyle. Spend wisely.",
  "Dominate the day before it dominates you.",
  "Be addicted to the process and the results chase you.",
  "Soft choices, hard life. Hard choices, soft life. Choose.",
  "Nobody's stopping you but the guy in the mirror. Move him.",
  "Hustle until your haters ask if you're hiring.",
  "Closed mouths don't get fed. Open it and ask for the sale.",
  "Run your race so hard the competition forgets it's a race.",
  "You're one phone call from a different life. Make it.",
  "Get comfortable being uncomfortable. That's where you grow.",
  "Sharpen the axe, then swing like you mean it.",
  "Empires aren't built on good intentions. Build on action.",
  "Be the storm, not the guy waiting for it to pass.",
  "The only easy day was yesterday. Earn today.",
  "Beast mode isn't a phase, it's a standard. Set it.",
  "Stop waiting for permission. Take the shot.",
  "Your potential is screaming. Stop hitting snooze on it.",
  "Lions don't lose sleep over the opinions of sheep. Hunt.",
  "Do the work nobody sees so you live the life everybody wants.",
  "Today is a deposit into the man you're becoming. Max it out.",
  "Sweat equity never goes out of style. Pour it in.",
  "Fortune favors the bold and ignores the comfortable.",
  "Make the hard call first. The rest of the day bows to it.",
  "You can have results or excuses, never both. Pick results.",
  "Grind in private, shine in public.",
  "The man who outworks everyone fears no one.",
  "Don't count the dials. Make the dials count.",
  "Stay hungry. Full men don't hunt.",
  "Be a problem for your competition today.",
  "Discipline today is freedom tomorrow. Pay it forward.",
  "Win or learn, never lose. Then run it back harder.",
  "Your name should mean closer. Go earn it.",
  "Quit waiting to feel ready. Ready is built in motion.",
  "Outlast, outwork, out-believe. That's the whole formula.",
  "Show the calendar who's boss. Fill it with wins.",
  "Be relentless on the days you want it least.",
  "The market rewards courage. Bring yours today.",
  "Crush the easy task fast, then go kill the hard one.",
  "Make excellence boring by doing it every single day.",
  "Pressure is a privilege. Step into it and perform.",
  "You don't rise to your goals, you fall to your habits. Build better.",
  "Burn the boats. Forward is the only direction now.",
  "Today's grind funds tomorrow's freedom. Clock in.",
  "Be the man your goals require, not the one your mood prefers.",
  "Speed and reps. That's the cheat code. Use it.",
  "The dip is where the average quit. Push through it.",
  "Make the day flinch. Hit it first and hit it hard.",
  "No one's busy when their dream is on the line. Get to work.",
  "You're built for this. Now go prove it to yourself.",
  "Be too busy winning to entertain doubt.",
  "Hard now, easy later. Soft now, sorry later.",
  "The phone is a money printer. Go press the buttons.",
  "Stop managing your comfort and start manufacturing wins.",
  "Effort is the rent you pay for the life you want. Pay up.",
  "Be the guy who shows up when nobody's watching.",
  "Aim higher than makes you comfortable. Then climb.",
  "Hunt like you're hungry, because someday you might be.",
  "The work whispers your name. Answer it.",
  "Greatness doesn't take days off. Neither should you.",
  "Make the call. Eat the no. Repeat until rich.",
  "Doubt kills more dreams than failure ever will. Move anyway.",
  "Be the exception, not the average. It pays better.",
  "Today is undefeated until you decide to win it.",
  "Don't shrink to fit the room. Make the room bigger.",
  "Your grind is your signature. Sign loud.",
  "Get 1% better and watch a year change your life.",
  "Hesitate and the deal goes to a man who didn't.",
  "Be unreasonable about your goals and ruthless with your time.",
  "The only person you have to beat is yesterday's you.",
  "Pick up the iron and pick up the phone. Both build men.",
  "Win the rep in front of you. The mountain takes care of itself.",
  "Make today expensive for your competition.",
  "Stop waiting for the perfect moment. Make this one count.",
  "The hard road is the only one that leads somewhere worth going.",
  "Be feared by your goals, not your excuses.",
  "Every champion was once a contender who refused to quit.",
  "Show up so consistently it looks like luck.",
  "Action cures fear. So act, then act again.",
  "The grind is lonely at the top because most won't climb. Climb.",
  "Don't pray for an easy life. Pray for the strength to crush a hard one.",
  "Money is a scoreboard. Go put points up.",
  "Be the storm the competition prays never comes.",
  "Make the first hour brutal and the rest of the day's easy.",
  "Your comeback is built in the reps nobody applauds.",
  "Conquer the morning and the day surrenders.",
  "No half-reps. No half-days. No half-men.",
  "Get obsessed with the work and the rewards get obsessed with you.",
  "Be a closer in a world full of talkers.",
  "The phone doesn't ring itself. Make it ring with your wins.",
  "Tired is not a reason. It's an excuse in a costume.",
  "Run toward the hard thing. That's where the money sleeps.",
  "You don't need more time, you need more urgency.",
  "Every dial is a lottery ticket you control. Buy more.",
  "Make your discipline louder than your distractions.",
  "Win today and let tomorrow worry about itself.",
  "The man who masters mornings masters his life.",
  "Be the reason your goals get nervous.",
  "Stop building someone else's dream on company time. Build yours.",
  "Outhustle yesterday. That's the only competition that matters.",
  "Pain you choose builds you. Pain you avoid builds nothing.",
  "Dial like rent is due, because someday it always is.",
  "Be the hardest no to get and the easiest yes to keep.",
  "The work is the prayer. Get on your knees and grind.",
  "Make the day so productive it owes you interest.",
  "Quit talking about the man you'll be. Go be him now.",
  "Hungry men move faster. Stay hungry.",
  "Be relentless in the pursuit, gracious in the win.",
  "Closers eat first. Get to the front of the line.",
  "The mountain doesn't move. You climb. Start climbing.",
  "Every legend started exactly where you're standing. Move.",
  "Be a machine when others are making excuses.",
  "Today you build proof that you don't quit.",
  "Make momentum your default setting.",
  "The bold get bruised, but the timid get nothing.",
  "Win the boring days. That's where empires hide.",
  "You're not behind. You're early for the work most won't do.",
  "Crush the call you've been avoiding. Freedom's on the other side.",
  "Hard work is a magnet for luck. Get magnetic.",
  "Be too disciplined to fail and too hungry to stop.",
  "The grind chose you. Now choose it back, daily.",
  "Make the number, then make a bigger one.",
  "Be the man who turns pressure into paychecks.",
  "Your excuses bore me, and they bore your future too.",
  "Every closed door is a hallway. Keep walking.",
  "Strike first, strike hard, follow up harder.",
  "The reps don't lie and they don't take days off.",
  "Be feared by the lazy and respected by the great.",
  "Money flows to the man who moves with conviction.",
  "Get up earlier than your problems.",
  "Make the impossible your warm-up.",
  "The only failure is the call you never made.",
  "Be a savage with your schedule and a gentleman with your wins.",
  "Greatness is built on the days you didn't feel like it.",
  "Stop waiting to be picked. Pick yourself and pick up the phone.",
  "Today belongs to the man who wants it most. Want it more.",
  "Be the closer the room didn't see coming.",
  "Run the play until it works, then run it harder.",
  "Discipline is choosing what you want most over what you want now.",
  "Make your mornings violent and your evenings earned.",
  "The market bows to consistency. Be consistent.",
  "Hustle now so your kids never have to.",
  "Be the man who finishes what scared everyone else.",
  "One call can flip a quarter. Make it like you mean it.",
  "Sharpen your edge daily or the competition dulls you.",
  "Don't manage the day. Conquer it.",
  "Be relentless. Relentless always cashes out.",
  "Your habits are voting for your future. Vote like a champion.",
  "Get loud with your work and quiet with your complaints.",
  "The grind is the gift. Unwrap it every morning.",
  "Be the standard, not the exception to it.",
  "Today's discomfort is tomorrow's flex. Earn the flex.",
  "Make the call that makes the month.",
  "Win the reps nobody's counting and the world starts counting you.",
  "Be a problem the market can't solve except by paying you.",
  "Fortune punishes the hesitant. Move with intent.",
  "Outlast the dip and the doubters both.",
  "The phone is your sword. Swing it all day.",
  "Get addicted to the climb, not the comfort.",
  "Be the man who shows up first and leaves last.",
  "Make the hard thing your specialty.",
  "Today you out-dial, out-work, and out-believe everyone.",
  "Stop renting time to fear. Own your hours.",
  "Be the kind of busy that builds an empire.",
  "Every great run starts with a brutal first step. Take it.",
  "Sweat is just weakness leaving on commission.",
  "Be the closer who never blinks.",
  "Hunt today like the freezer's empty.",
  "The reps compound. Stack them ruthlessly.",
  "Be unbothered by no and unstoppable toward yes.",
  "Make discipline your religion and results your reward.",
  "Today is a weapon. Aim it at your goals.",
  "The grind owes you nothing, but it pays the persistent.",
  "Be a force, not a forecast.",
  "Make the calls until the calls make you.",
  "You're built for the hard road. Stop looking for the easy one.",
  "Out-effort your excuses every single morning.",
  "Be the man your goals are afraid of.",
  "Pressure off the bold is just fuel. Burn it.",
  "Don't wait for opportunity. Out-work it into existence.",
  "Win the dial in front of you and the day follows.",
  "Be relentless when it's boring. That's the secret.",
  "The closer mindset: every problem is a sale waiting to happen.",
  "Make the work non-negotiable and the wins inevitable.",
  "Today the lazy lose ground. Take it.",
  "Be too locked in to be lucky and too disciplined to be denied.",
  "Hunger beats talent that's full and comfortable.",
  "Get up and get after it before the world tells you no.",
  "Be a savage on the phone and a king at home.",
  "Make every hour answer to your ambition.",
  "The grind is the price of the man you want to be. Pay it.",
  "Be the comeback nobody saw coming.",
  "Run it back harder every single day.",
  "Closers don't have bad days, they have learning ones.",
  "Make the dial. Make the day. Make the year.",
  "Be obsessed enough to scare your old self.",
  "Today is built for men who refuse to fold.",
  "Outwork the room and let the results do the bragging.",
  "Be the hardest worker and the easiest to root for.",
  "The phone is heavy only to men who won't lift it.",
  "Make your discipline the loudest thing in the building.",
  "Stop circling the work. Land on it and dominate.",
  "Be relentless, be ready, be paid.",
  "The man who keeps dialing keeps winning.",
  "Make today a flex your future self brags about.",
  "Hunt the hard call first and the day gets soft.",
  "Be too busy building to entertain doubt.",
  "Greatness is reps plus refusal to quit. Do both.",
  "Today you set the pace. Make it brutal.",
  "Be the wolf, not the worry.",
  "Every dial is a brick. Build the empire.",
  "Don't ask if you can. Decide that you will.",
  "Make the grind your home field advantage.",
  "Be relentless when the scoreboard's against you.",
  "The market respects effort. Show it some.",
  "Outhustle the version of you that wanted to coast.",
  "Be a closer in a world of maybes.",
  "Today you earn the right to win tomorrow.",
  "Make the call that changes the story.",
  "Be the man who never needs a reason to work.",
  "Pressure builds you or buries you. Choose built.",
  "Get loud with results and silent with excuses.",
  "Be the reason the leaderboard needs a bigger top.",
  "Run the day like a man with something to prove.",
  "The grind doesn't negotiate. Neither should you.",
  "Make discomfort your daily appointment. Never miss it.",
  "Be relentless until the relentless looks like luck.",
  "Today the dials decide. Make them count.",
  "Hunt, close, repeat. That's the whole religion.",
  "Be the standard others measure themselves against.",
  "Make the first call before fear wakes up.",
  "The man on a mission moves before he feels ready.",
  "Be too disciplined to drift.",
  "Outwork the doubt out of your own head.",
  "Today you stack proof that you're built different.",
  "Be a savage with the schedule and merciless with excuses.",
  "Make the grind a habit and the wins a routine.",
  "The phone rewards the brave. Be brave all day.",
  "Be the man who turns Mondays into momentum.",
  "Hunt the day with everything you've got.",
  "Make discipline so normal it feels like breathing.",
  "Be relentless, be ruthless with time, be rich.",
  "Today you out-dial yesterday or you stand still.",
  "Be the closer the market can't shake.",
  "Make the hard yes your favorite sound.",
  "The grind is the gym. Show up and get strong.",
  "Be too hungry to settle and too smart to quit.",
  "Win the morning reps and the day belongs to you.",
  "Make every no a deposit toward the yes.",
  "Be the man who answers the call to greatness daily.",
  "Today's effort writes tomorrow's headline. Make it loud.",
  "Hunt like a closer, recover like a champion.",
  "Be relentless on the boring Tuesdays.",
  "Make the work your weapon and the day your target.",
  "The empire is built one dial at a time. Start dialing.",
  "Be the storm that the comfortable never survive.",
  "Today you choose hard, and hard chooses winners.",
  "Make the calls your competition is too scared to make.",
  "Be the man whose discipline embarrasses his doubts.",
  "Run at the goal until the goal runs out of room.",
  "Be relentless, and let relentless pay the bills.",
  "Make today the day the market learns your name.",
  "Hunt now. Rest when the goal is bleeding.",
  "Be the closer, the grinder, the standard. Be all three today.",
  "Out-work the world and let the scoreboard explain why.",
  "Make discipline your default and success your shadow.",
  "Be the man who never lets a hard day win.",
  "Today you build the legend one rep at a time.",
  "Hunt the call, eat the no, stack the yes.",
  "Be relentless until your goals beg for mercy.",
  "Make the grind beautiful by never skipping it.",
  "The phone is the path. Walk it all day.",
  "Be too locked in to lose today.",
  "Make every minute a down payment on the dream.",
  "Hunt hard, close clean, repeat forever.",
  "Be the man your future is begging you to become. Today.",
  "Set the tone before the day sets it for you.",
  "Be the guy who dials when everyone else is doubting.",
  "Make the hard call your first call, every morning.",
  "Win the rep, win the hour, win the war.",
  "Be relentless when the room goes quiet.",
  "Your work ethic is your reputation. Make it legendary.",
  "Out-grind your yesterday and the future bends your way.",
  "Be the man who turns rejection into rocket fuel.",
  "Make the dials until the doubt taps out.",
  "Discipline carries you when motivation clocks out.",
  "Be the closer who treats every call like the big one.",
  "Today the soft fold. Be the man who never does.",
  "Make excellence your minimum, not your goal.",
  "Hunt the day before your alarm even finishes.",
  "Be relentless, be hungry, be the one they study.",
  "The grind separates men from intentions. Pick up the phone.",
  "Make your name a verb for closing.",
  "Be unreasonable today. Reasonable men stay broke.",
  "Out-work the talent and out-last the lucky.",
  "Every yes is hiding behind a stack of dials. Dig.",
  "Be the storm, the standard, and the scoreboard's nightmare.",
  "Make today a clinic on not quitting.",
  "Hunt like the comeback depends on it. It does.",
  "Be too busy closing to count the no's.",
  "Discipline now, deals later, freedom forever.",
  "Be the man who makes hard look easy by doing it daily.",
  "Run the day so hard it remembers your name.",
  "Make the call, take the swing, own the result.",
  "Be relentless until relentless is just who you are.",
  "Win the dial. Win the deal. Win the decade.",
  "Be the hardest worker, the calmest closer, the last to quit.",
  "Make the grind your love language.",
  "Hunt today. The freezer fills itself for nobody.",
  "Be the man your goals can't outrun.",
  "Today you build proof. Tomorrow you live it.",
];

/** Today's hype line (stable per calendar day, rotates yearly). */
export function todaysHype(): string {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((now.getTime() - start.getTime()) / 86400000);
  return HYPE_LINES[dayOfYear % HYPE_LINES.length];
}
